function handles_breath = initBreathPlots()
%INITBREATHPLOTS 
% Generated by ChatGPT
% Figure 20 - Differentiated Phase
figure(20)
hPhase = plot(nan,nan);
xlabel("Time [s]"); title("Differentiated Phase");

% Figure 21 - Displacement
figure(21)
hDisp1 = plot(nan,nan); hold on
hDisp2 = plot(nan,nan,'LineWidth',2); hold off
title("Displacement [mm]");

% Figure 22 - SSTFT
figure(22)
hImg = imagesc(nan,nan,nan); axis xy
colormap(flip(gray)); colorbar
hRidge = line(nan,nan,'Color','r','LineWidth',1.5);
ylabel("Breath Rate [BPM]"); xlabel("Time [s]");
title("Synchrosqueezed STFT with detected ridge");

% zapisz uchwyty do struktury
handles_breath.phase = hPhase;
handles_breath.disp1 = hDisp1;
handles_breath.disp2 = hDisp2;
handles_breath.sstftImg = hImg;
handles_breath.sstftRidge = hRidge;
end

