function plotBreathResults(results, handles)
% Generated by ChatGPT
    % results - struct zwrócony z extract_breath
    % handles - struct z uchwytami do wykresów (inicjalizowany raz)
    
    % 1. Differentiated Phase
    set(handles.phase, 'XData', results.phase.time, ...
                       'YData', results.phase.data);
    
    % 2. Displacement
    set(handles.disp1, 'XData', results.displacement.time, ...
                       'YData', results.displacement.data1);
    set(handles.disp2, 'XData', results.displacement.time, ...
                       'YData', results.displacement.data2);
    
    % 3. SSTFT
    set(handles.sstftImg, 'XData', results.sstft.t, ...
                          'YData', results.sstft.f, ...
                          'CData', db(results.sstft.spectrogram));
    set(handles.sstftRidge, 'XData', results.sstft.t, ...
                            'YData', results.sstft.ridge);
    
    drawnow limitrate; % szybkie odświeżanie
end