function plotBreathResults(results, handles, opts)
% Generated by ChatGPT
    % results - struct zwrócony z extract_breath
    % handles - struct z uchwytami do wykresów (inicjalizowany raz)

    arguments
        results 
        handles 
        opts.RTrows = []
    end
    
    % % 1. Differentiated Phase
    % set(handles.phase, 'XData', results.phase.time, ...
    %                    'YData', results.phase.data);
    
    % 2. Displacement
    set(handles.disp1, 'XData', results.displacement.time, ...
                       'YData', results.displacement.data1);
    set(handles.disp2, 'XData', results.displacement.time, ...
                       'YData', results.displacement.data2);
    if(~isempty(opts.RTrows))
        set(handles.disp1.Parent.Title, 'String', join(['Displacement [mm],  RT rows: ' strrep(string(opts.RTrows), " ", ", ")]))
    end
    
    % 3. SSTFT
    cdata_sstft = results.sstft.spectrogram;
    cdata_sstft = abs(cdata_sstft);
    thresh = quantile(nonzeros(cdata_sstft),0.5,"all");
    cdata_sstft(cdata_sstft < thresh) = thresh;
    cdata_sstft = db(cdata_sstft);
    set(handles.sstftImg, 'XData', results.sstft.t, ...
                          'YData', results.sstft.f, ...
                          'CData', cdata_sstft);
    set(handles.sstftImg.Parent, 'XLim', [min(results.sstft.t) max(results.sstft.t)], ...
                              'YLim', [min(results.sstft.f) max(results.sstft.f)]);

    set(handles.sstftRidge, 'XData', results.sstft.t, ...
                            'YData', results.sstft.ridge);
    set(handles.sstftImg.Parent.Title, 'String', join(['Synchrosqueezed STFT; Breath Rate: ' string(mean(results.sstft.ridge)) ' BPM']))
    
    drawnow limitrate; % szybkie odświeżanie
end