function plotHeartbeatResults(results, handles)
    % 1. Filtered Phase Differentiation
    set(handles.filteredPhase, 'XData', results.filteredPhase.time, ...
                               'YData', results.filteredPhase.data);

    % 2. STFT
    set(handles.stft, 'XData', results.stft.t, ...
                      'YData', results.stft.f, ...
                      'CData', results.stft.spectrogram);

    % 3. Extracted signal from STFT
    set(handles.extractedSignal.pred, 'XData', results.extractedSignal.t, ...
                                      'YData', results.extractedSignal.predicted);
    set(handles.extractedSignal.avail, 'XData', results.extractedSignal.t, ...
                                       'YData', results.extractedSignal.available);

    % 4. Synchrosqueezed STFT
    set(handles.sstft.img, 'XData', results.sstft.t, ...
                           'YData', results.sstft.f, ...
                           'CData', db(results.sstft.spectrogram));
    set(handles.sstft.ridge, 'XData', results.sstft.t, ...
                             'YData', results.sstft.ridge);

    drawnow limitrate;
end