results_path = "results" + filesep + "meas2" + filesep;
files = dir(results_path + "*.mat");

handles_breath = initBreathPlots();
handles_heartbeat = initHeartbeatPlots();

breath_rate_cell = {};
breath_rate_time_ax_cell = {};
heart_rate_cell = {};
heart_rate_time_ax_cell = {};

for k = 1:length(files)

    file = load([files(k).folder filesep files(k).name]);

    breath_rate = file.results_breath.sstft.ridge;
    breath_rate_time_ax = seconds(file.results_breath.sstft.t) + file.fragment_date_start;
    heart_rate = file.results_heartbeat.sstft.ridge;
    heart_rate_time_ax = seconds(file.results_heartbeat.sstft.t) + file.fragment_date_start;

    breath_rate_cell{end+1} = breath_rate;
    breath_rate_time_ax_cell{end+1} = breath_rate_time_ax;
    heart_rate_cell{end+1} = heart_rate;
    heart_rate_time_ax_cell{end+1} = heart_rate_time_ax;

    plotBreathResults(file.results_breath, handles_breath, "RTrows", file.RTrow_vect);
    plotHeartbeatResults(file.results_heartbeat, handles_heartbeat);

    % pause(1);
end



%% full breath rate

% Generated by ChatGPT

% preallocate
all_times = [];
all_values = [];

cut_edges_breath = [0.1 0.9];

for k = 1:length(breath_rate_cell)
    t = breath_rate_time_ax_cell{k};
    v = breath_rate_cell{k};

    % cut edges: np. odetnij 10% z początku i końca
    N = numel(t);
    idx_keep = round(cut_edges_breath(1)*N) : round(cut_edges_breath(2)*N);
    idx_keep(idx_keep == 0) = 1;

    t_mid = t(idx_keep);
    v_mid = v(idx_keep);

    % append
    all_times = [all_times; t_mid(:)];
    all_values = [all_values; v_mid(:)];
end

% posortuj po czasie (na wszelki wypadek)
[all_times, idx] = sort(all_times);
all_values = all_values(idx);

TT = timetable(all_times, all_values);
% wymuś równą siatkę czasową np. co 1 sekundę i uśrednij nakładające się próbki
TTu = retime(TT, 'regular', 'mean', 'TimeStep', seconds(1));

% figure(300);
% plot(TTu.all_times, TTu.all_values);
% xlabel("Time");
% ylabel("Breath Rate [BPM]");

% teraz masz pełny wykres
figure(300);
plot(all_times, all_values)
datetick('x','HH:MM:SS') % ładne formatowanie czasu
xlabel("Time");
ylabel("Breath Rate [BPM]");
title("Full Breath Rate");

%% full heart rate

% Generated by ChatGPT

% preallocate
all_times = [];
all_values = [];

cut_edges_heartbeat = [0.3 0.9];

for k = 1:length(breath_rate_cell)
    t = heart_rate_time_ax_cell{k};
    v = heart_rate_cell{k};

    % cut edges: np. odetnij 10% z początku i końca
    N = numel(t);
    idx_keep = round(cut_edges_heartbeat(1)*N) : round(cut_edges_heartbeat(2)*N);
    idx_keep(idx_keep == 0) = 1;

    t_mid = t(idx_keep);
    v_mid = v(idx_keep);

    % append
    all_times = [all_times; t_mid(:)];
    all_values = [all_values; v_mid(:)];
end

% posortuj po czasie (na wszelki wypadek)
[all_times, idx] = sort(all_times);
all_values = all_values(idx);

TT = timetable(all_times, all_values);
% wymuś równą siatkę czasową np. co 1 sekundę i uśrednij nakładające się próbki
TTu = retime(TT, 'regular', 'mean', 'TimeStep', seconds(1));

% figure(800);
% plot(TTu.all_times, TTu.all_values);
% xlabel("Time");
% ylabel("Heart Rate [BPM]");

figure(800);
plot(all_times, all_values)
datetick('x','HH:MM:SS') % ładne formatowanie czasu
xlabel("Time");
ylabel("Heart Rate [BPM]");
title("Full Heart Rate");


%% load and process reference breath and heart rate

% Generated by ChatGPT
% ========================
%  1. Referencja oddechu
%  ========================
ref_breath_path = "reference" + filesep + "Głos 072.m4a";
[audio, fs] = audioread(ref_breath_path);

% Obwiednia amplitudy (energy envelope)
env = abs(hilbert(audio));
env = movmean(env, round(0.2*fs));   % wygładzenie (200 ms okno)

t_audio = (0:length(env)-1)/fs;

% Szacowanie częstości oddechu w BPM (opcjonalne)
% metoda: FFT na obwiedni w zakresie typowych oddechów
nfft = 2^nextpow2(length(env));
f = (0:nfft-1)/nfft*fs;
Y = abs(fft(env,nfft));
breath_band = (f>=0.1 & f<=1.0);   % 0.1-1 Hz (6-60 BPM)
[~,idx] = max(Y(breath_band));
freq_breath = f(breath_band);
ref_breath_BPM = freq_breath(idx)*60;

figure;
plot(t_audio, env);
xlabel("Time [s]");
ylabel("Envelope amplitude");
title(sprintf("Breathing envelope (peak freq ~ %.1f BPM)", ref_breath_BPM));

%% ========================

% Generated by ChatGPT
% 2. Referencja tętna (parsowanie poprawne)

ref_heartbeat_path  = "reference" + filesep + "Phaser rec 1.09 19_20.txt";
rawT = readtable(ref_heartbeat_path, 'Delimiter','\n', 'ReadVariableNames', false);

% Rozdziel kolumny spacjami
parts = split(rawT.Var1);

% Usunięcie pustych kolumn (bo między danymi są podwójne spacje)
parts = parts(:, all(parts~=""));

% Teraz:
% parts(:,1) -> numer uderzenia
% parts(:,2) -> czas absolutny (hh:mm.ss)
% parts(:,3) -> odstęp między uderzeniami (IBI)

beat_idx   = str2double(parts(:,1));
time_str   = parts(:,2);
ibi_str    = parts(:,3);

% Zamiana czasu na sekundy
beat_times = seconds(duration(time_str,'InputFormat','mm:ss.SS'));

% Inter-beat intervals (IBI)
ibi = seconds(duration(string(ibi_str),'InputFormat', "mm:ss.SS"));     % [s]
inst_HR = 60 ./ ibi;           % [BPM]
t_HR = beat_times;             % czas dla każdego beatu

% Interpolacja do osi czasu (np. co 0.1 s)
t_uniform = 0:0.1:max(beat_times);
HR_uniform = interp1(t_HR, inst_HR, t_uniform, 'linear', 'extrap');

% Wykres
figure;
plot(t_HR, inst_HR, 'o-', 'DisplayName',"Beat-to-beat HR"); hold on;
plot(t_uniform, HR_uniform, '-', 'LineWidth',1.5, 'DisplayName',"Interpolated HR");
xlabel("Time [s]");
ylabel("Heart Rate [BPM]");
title("Reference heart rate from stopwatch");
legend show; grid on;