% Generated by ChatGPT (partially)

% actual measurment using hardware
% sc = SignalCapturer("TotalRecLength",2,"FrameLength",1.87, "DoSave",0);

% simulation of recording
sc = SignalCapturerSimulator("TotalRecLength",2);

clear f1 f2 hBreath hHeartbeat
close all
% delete(pool);
if(~exist("pool", "var"))
    pool = parpool("Processes");
end

sc.configure();

windowSize = 2;       % number of frames in analysis window (min. 2)
hopSize = 1;          % step size in frames (min. 1)
sigBuffer = {};       % FIFO buffer for radar signals
timeBuffer = {};      % FIFO buffer for raw sc.times_post_tx
startTimes = [];      % system timestamps (one per frame)
counter = 0;          % frame counter

handles_breath = initBreathPlots();
handles_heartbeat = initHeartbeatPlots();


tic; % global reference for system time measurement

while true
    % --- system timestamp BEFORE recording ---
    frameStartSys = toc;   % time in seconds relative to loop start

    % --- acquisition step ---
    sc.record();
    RT = fft(sc.data);
    [radar_signal, RT_row] = choose_RT_row(RT);

    % --- store signal and frame start time ---
    sigBuffer{end+1}  = radar_signal;
    timeBuffer{end+1} = sc.times_post_tx;  % raw local times
    startTimes(end+1) = frameStartSys;     % absolute system start

    % keep only the last windowSize frames
    if numel(sigBuffer) > windowSize
        sigBuffer  = sigBuffer(end-windowSize+1:end);
        timeBuffer = timeBuffer(end-windowSize+1:end);
        startTimes = startTimes(end-windowSize+1:end);
    end

    % --- frame counter ---
    counter = counter + 1;

    % --- trigger analysis every hopSize frames ---
    if counter >= hopSize && numel(sigBuffer) == windowSize

        % plot figures
        if(exist("f1", "var"))
            results_breath = fetchOutputs(f1);
            results_heartbeat = fetchOutputs(f2);
            
            plotBreathResults(results_breath, handles_breath);
            plotHeartbeatResults(results_heartbeat, handles_heartbeat);

        end


        % normalize startTimes so that the first frame in window starts at 0
        baseTime = min(startTimes);

        adjustedTimes = {};
        for k = 1:numel(timeBuffer)
            adjustedTimes{end+1} = timeBuffer{k} + (startTimes(k) - baseTime);
        end

        % concatenate buffered frames into one longer signal and time axis
        long_signal = cat(2, sigBuffer{:});
        long_time   = cat(2, adjustedTimes{:});

        % analysis in background
        f1 = parfeval(pool, @extract_breath, 1, long_signal, sc.prf, sc.fc, long_time);
        f2 = parfeval(pool, @extract_heartbeat, 1, long_signal, sc.prf, long_time);
    
        futures = [futures f1 f2];  % futures collection

        % reset frame counter -> offsets will be recomputed fresh for next window
        counter = 0;
    end
end
