function x_filled = fill_gap_ar_bidirectional(x, p)

% % % % Generated by ChatGPT
% x – vector with NaNs at gap locations (only one gap allowed)
% p – order of the AR model (e.g., 20, 50… see tips below)
%
% Returns: x_filled – signal with gap filled based on bidirectional AR

    x = x(:);
    nanmask = isnan(x);

    % --- fragment przed przerwą
    idx_gap = find(nanmask);
    gap_start = idx_gap(1);
    gap_end   = idx_gap(end);

    x_before = x(1:gap_start-1);
    x_after  = x(gap_end+1:end);

    % --- model forward (z próbek przed przerwą)
    [Af, ~] = aryule(x_before, p);

    % prognoza forward przez długość przerwy
    xf = zeros(gap_end-gap_start+1,1);
    hist = x_before(end:-1:end-p+1);
    for k = 1:length(xf)
        xf(k) = -Af(2:end)*hist;
        hist = [xf(k); hist(1:end-1)];
    end

    % --- model backward (z próbek po przerwą, odwrócone)
    x_after_rev = flipud(x_after);
    p_backward = p; 
    p_backward(p_backward > length(x_after_rev)) = length(x_after_rev); % fix to not get error
    [Ab, ~] = aryule(x_after_rev, p_backward);

    xb = zeros(gap_end-gap_start+1,1);
    hist = x_after_rev(end:-1:end-p_backward+1);
    for k = 1:length(xb)
        xb(k) = -Ab(2:end)*hist;
        hist = [xb(k); hist(1:end-1)];
    end
    xb = flipud(xb); % odwróć z powrotem

    % --- łączenie forward/backward
    n = (0:length(xf)-1)';
    alpha = linspace(1,0,length(xf))';  % 1 na początku, 0 na końcu
    xgap = alpha.*xf + (1-alpha).*xb;

    % --- scal całość
    x_filled = x;
    x_filled(gap_start:gap_end) = xgap;
end
