function x_filled_full = fill_gaps_ar(x, p, opts)

% % % % Generated by ChatGPT
% x – vector with NaNs at gap locations
% p – order of the AR model (e.g., 20, 50… see tips below)
%
% Returns: x_filled – signal with gaps filled

arguments
    x
    p
    opts.TrainSegmentsSeparately = 1; % train each segment separately
    opts.NLastTrainSegments = 5; % how many last segments to get train data
end

    p_desired = p;

    x = x(:); % kolumna

    nanmask = isnan(x);
    if all(~nanmask)
        x_filled_full = x;
        return;
    end

    x_filled_full = zeros(size(x));

    % taking segment start-end idxes
    [segment_starts] = logical2segmentIdxes(~isnan(x));
    % place the last segment at first
    x_filled_full(segment_starts(end):end) = x(segment_starts(end):end);
    N_last_segments_train = opts.NLastTrainSegments;

    if(~opts.TrainSegmentsSeparately)
        segment_starts = [1];
        N_last_segments_train = 1;
    end



    for segNr = 1:length(segment_starts)
        % traning samples + break
        if(segNr == length(segment_starts))
            max_sample_of_segment = length(x);
        else
            max_sample_of_segment = segment_starts(segNr+1)-1;
        end
        x_SegmentAndBreak = x(segment_starts(segNr):max_sample_of_segment);
        nanmask_segment = isnan(x_SegmentAndBreak);

        % next, everything is the same in loop as in the case of not diving x into
        % segments, but there is x_SegmentAndBreak instead of x, and
        % nanmask_segment instead of nanmask
    
            mu = mean(x_SegmentAndBreak(~nanmask_segment));
            xz = x_SegmentAndBreak - mu;
            
            %%%%%%
            % x_train = xz(~nanmask_segment);
            %%%%%%
            if(segNr >= N_last_segments_train)
                segNrStartTrain = segNr - N_last_segments_train + 1;
            else
                segNrStartTrain = 1;
            end
            x_train_idx = segment_starts(segNrStartTrain):max_sample_of_segment;
            x_train = x(x_train_idx);
            x_train = x_train(~isnan(x_train));
            x_train = x_train - mean(x_train);
            %%%%

            if numel(x_train) <= p_desired
                error('Za mało danych obserwowanych do estymacji AR(p). Zmniejsz p.');
            end
            [A, ~] = aryule(x_train, p);  % A = [1 a1 a2 ... ap]
            x_filled = xz;
            N = numel(x_SegmentAndBreak);
    
            n = 1;
            while n <= N
                if ~nanmask_segment(n)
                    n = n + 1;
                    continue;
                end
        
                % break start
                gap_start = n;
                % break end
                while n <= N && nanmask_segment(n)
                    n = n + 1;
                end
                gap_end = n - 1;
        
                % we need to have at leat p available samples before break
                if gap_start <= p
                    error('Pierwsza przerwa zaczyna się zbyt wcześnie, brak %d próbek historii.', p);
                end
        
                % fill each sample in break
                for k = gap_start:gap_end
                    past = x_filled(k-1:-1:k-p);           % [x(k-1), x(k-2), ..., x(k-p)]
                    x_filled(k) = -A(2:end) * past;        % x(k) = -sum_{i=1..p} a_i * x(k-i)
                end
            end

            % restore offset
            x_filled = x_filled + mu;

        % assign a part of predicted data
        x_filled_full(segment_starts(segNr):max_sample_of_segment) = x_filled;

    end



    % %%%% OLD version
    % 
    % 
    % % 1) Detrending: AR działa lepiej dla sygnału o ~zerowej średniej
    % mu = mean(x(~nanmask));
    % xz = x - mu;
    % 
    % % 2) Uczenie AR tylko na próbkach dostępnych (bez NaN)
    % %    Uwaga: 'aryule' jest w Signal Processing Toolbox
    % x_train = xz(~nanmask);
    % if numel(x_train) <= p_desired
    %     error('Za mało danych obserwowanych do estymacji AR(p). Zmniejsz p.');
    % end
    % [A, ~] = aryule(x_train, p);  % A = [1 a1 a2 ... ap]
    % 
    % % 3) Rekurencyjne wypełnianie braków: e[n]=0 (predykcja)
    % x_filled = xz;
    % N = numel(x);
    % 
    % n = 1;
    % while n <= N
    %     if ~nanmask(n)
    %         n = n + 1;
    %         continue;
    %     end
    % 
    %     % początek przerwy
    %     gap_start = n;
    %     % koniec przerwy
    %     while n <= N && nanmask(n)
    %         n = n + 1;
    %     end
    %     gap_end = n - 1;
    % 
    %     % musimy mieć co najmniej p znanych próbek przed przerwą
    %     if gap_start <= p
    %         error('Pierwsza przerwa zaczyna się zbyt wcześnie, brak %d próbek historii.', p);
    %     end
    % 
    %     % wypełnianie każdej próbki w przerwie
    %     for k = gap_start:gap_end
    %         past = x_filled(k-1:-1:k-p);           % [x(k-1), x(k-2), ..., x(k-p)]
    %         x_filled(k) = -A(2:end) * past;        % x(k) = -sum_{i=1..p} a_i * x(k-i)
    %     end
    % end
    % 
    % % 4) Przywróć średnią
    % x_filled = x_filled + mu;
end
