function x_filled = fill_gaps_ar(x, p)

% % % % Generated by ChatGPT
% x – vector with NaNs at gap locations
% p – order of the AR model (e.g., 20, 50… see tips below)
%
% Returns: x_filled – signal with gaps filled



    x = x(:); % kolumna
    nanmask = isnan(x);
    if all(~nanmask)
        x_filled = x;
        return;
    end

    % 1) Detrending: AR działa lepiej dla sygnału o ~zerowej średniej
    mu = mean(x(~nanmask));
    xz = x - mu;

    % 2) Uczenie AR tylko na próbkach dostępnych (bez NaN)
    %    Uwaga: 'aryule' jest w Signal Processing Toolbox
    x_train = xz(~nanmask);
    if numel(x_train) <= p
        error('Za mało danych obserwowanych do estymacji AR(p). Zmniejsz p.');
    end
    [A, ~] = aryule(x_train, p);  % A = [1 a1 a2 ... ap]

    % 3) Rekurencyjne wypełnianie braków: e[n]=0 (predykcja)
    x_filled = xz;
    N = numel(x);

    n = 1;
    while n <= N
        if ~nanmask(n)
            n = n + 1;
            continue;
        end

        % początek przerwy
        gap_start = n;
        % koniec przerwy
        while n <= N && nanmask(n)
            n = n + 1;
        end
        gap_end = n - 1;

        % musimy mieć co najmniej p znanych próbek przed przerwą
        if gap_start <= p
            error('Pierwsza przerwa zaczyna się zbyt wcześnie, brak %d próbek historii.', p);
        end

        % wypełnianie każdej próbki w przerwie
        for k = gap_start:gap_end
            past = x_filled(k-1:-1:k-p);           % [x(k-1), x(k-2), ..., x(k-p)]
            x_filled(k) = -A(2:end) * past;        % x(k) = -sum_{i=1..p} a_i * x(k-i)
        end
    end

    % 4) Przywróć średnią
    x_filled = x_filled + mu;
end
